CREATE EXTENSION IF NOT EXISTS pgcrypto;
INSERT INTO users(name, email, password, enabled, authority_id)
VALUES ('Andrey', 'andreyka@gmail.com', crypt('andrey123', gen_salt('bf')), true, 2),
       ('Bob', 'bobik@gmail.com', crypt('bobikk2', gen_salt('bf')), true, 2),
       ('Stephen', 'curry@gmail.com', crypt('stephcur7', gen_salt('bf')), true, 2),
       ('Natlus', 'makintoshev@gmail.com', crypt('pojo222', gen_salt('bf')), true, 2),
       ('Tomas', 'jerriev@gmail.com', crypt('tomandjerry', gen_salt('bf')), true, 2);
INSERT INTO orders (user_id, product_name, product_quantity, product_price, total_price, time)
VALUES (1, 'Apple iPhone 12', 1, 699, 699, CURRENT_TIMESTAMP),
       (1, 'Sonos One', 2, 199, 398, CURRENT_TIMESTAMP),
       (1, 'Sonos Beam', 2, 399, 798, CURRENT_TIMESTAMP),
       (2, 'HP Color LaserJet Enterprise MFP M477', 1, 629, 629, CURRENT_TIMESTAMP),
       (2, 'Alienware Aurora R10', 1, 2899, 2899, CURRENT_TIMESTAMP),
       (2, 'MacBook Air M1', 1, 1299, 1299, CURRENT_TIMESTAMP),
       (3, 'LG OLED CX', 2, 2499, 4998, CURRENT_TIMESTAMP),
       (3, 'Canon EOS R6', 1, 2499, 2499, CURRENT_TIMESTAMP),
       (3, 'HP Color LaserJet Enterprise MFP M477', 3, 629, 1887, CURRENT_TIMESTAMP),
       (3, 'Samsung Galaxy Tab S7+', 1, 849, 849, CURRENT_TIMESTAMP),
       (4, 'Samsung Galaxy S21', 2, 799, 1598, CURRENT_TIMESTAMP),
       (4, 'Canon EOS R5', 1, 3899, 3899, CURRENT_TIMESTAMP),
       (4, 'Sony PlayStation 5', 2, 499, 998, CURRENT_TIMESTAMP),
       (5, 'Canon PIXMA TR150', 4, 199, 796, CURRENT_TIMESTAMP),
       (5, 'Apple Watch Series 6', 2, 399, 798, CURRENT_TIMESTAMP),
       (5, 'Samsung Galaxy Watch 4 Classic', 1, 349, 349, CURRENT_TIMESTAMP);
INSERT INTO reviews (text, rating, user_id, product_id)
VALUES ('Good product!', 4.8, 1, 1),
       ('I bought it 1 year ago and it has already broken...', 2.7, 1, 14),
       ('There are some factory defects, occasionally you will have problems with this item', 3.1, 1, 23),
       ('Medium quality product, but price is not so expensive', 3.9, 2, 22),
       ('So expensive product! But it does not have competitors', 4.2, 2, 12),
       ('Just very good quality product, not a word more', 5, 2, 15),
       ('So amazing product, but price... so sad for the price', 4, 3, 8),
       ('5 out 5, Incredible!', 5, 3, 20),
       ('Takes up a lot of space, but in principle everything is fine', 4.4, 3, 22),
       ('No matter what anyone says, I really liked the product', 4.9, 3, 18),
       ('I do really like it!', 5, 4, 2),
       ('Product is expensive, but has high quality', 4.6, 4, 9),
       ('I did not like the design, but price and quality is ok', 4.5, 4, 3),
       ('Please change design of product, design is so ugly', 4.3, 5, 13),
       ('When i bought it, i thought this product was bad, but now... I have been using this since 2020 and all it is ok',
       4.7, 5, 4),
       ('Good quality product and price is not big', 4.8, 5, 25);